log/logger.go
=> [TD-10906]<fix>: fix log panic

schemaless/capi/opentsdb.go
=> [TD-10911]<fix>: remove the `put` string in the telnet protocol

db/commonpool/pool.go, go.mod, go.sum, log/logger.go, plugin/opentsdbtelnet/plugin.go, schemaless/capi/opentsdb.go, schemaless/capi/opentsdb_test.go, schemaless/opentsdb/telnet_test.go
=> remove the `\r` char in the telnet protocol

README-CN.md, README.md
offline reviewed by Haojun and Shuaiqiang
=> fix markdown link

benchmark/main.go, schemaless/capi/influxdb.go, schemaless/capi/locker.go, schemaless/capi/opentsdb.go, schemaless/capi/selectdb.go
=> [TD-11910]<enhance>: use global locks to limit thread bloat

db/async/row.go, go.mod, go.sum
=> [TD-12089]<fix>: Fix `select distinct(database_name) from log.vgroups_info` unexpected result

db/async/row.go, go.mod, go.sum
=> [TD-12157]<enhance>: support json type

db/async/row.go
=> [TD-12163]<fix>: use taos_is_update_query to determine if fetch data is required

BUILD-CN.md, BUILD.md, README-CN.md, README.md
=> docs: change version number to align with TDengine docs

log/logger.go, log/web.go, log/web_test.go, monitor/monitor.go, monitor/monitor_test.go, plugin/prometheus/plugin.go, plugin/prometheus/process.go
=> feat: modify monitor type

.gitignore, .pre-commit-config.yaml, README-CN.md, README.md
=> feat: update .gitignore for develop

README.md
change outdated link to current link
=> docs: update link in github readme

controller/ws/schemaless/schemaless.go, controller/ws/stmt/const.go, controller/ws/stmt/convert.go, controller/ws/stmt/convert_test.go, controller/ws/stmt/stmt.go, controller/ws/stmt/stmt_test.go, go.mod, go.sum
(cherry picked from commit e68bdd4b199a8cd4838798dae7503a49f6753e47)
=> feat: ws support get_tag_fields and get_col_fields

controller/rest/restful.go, plugin/prometheus/process.go
(cherry picked from commit 6a8103d10e431a5ef9fe7b0f058765a8a9629682)
=> fix: fix parsing timestamp

plugin/collectd/config.go
=> fix: disable collectd by default

controller/rest/error_resp.go, controller/rest/restful.go, controller/rest/restful_test.go, controller/ws/query/ws.go, controller/ws/schemaless/schemaless.go, controller/ws/stmt/stmt.go, controller/ws/tmq/tmq.go, controller/ws/ws/handler.go, controller/ws/wstool/error_test.go, controller/ws/wstool/log.go, controller/ws/wstool/log_test.go
=> fix: avoid negative values when setting back the clock

controller/ws/tmq/tmq.go, controller/ws/tmq/tmq_test.go
Jira: https://jira.taosdata.com:18080/browse/TD-
=> enh: optimize tmq poll

controller/ws/ws/stmt2.go, db/syncinterface/wrapper_test.go
Jira: https://jira.taosdata.com:18080/browse/TD-34046
=> fix: update stmt2 error handling to use TaosStmt2Error

.github/workflows/build.yml, .github/workflows/macos.yml, .github/workflows/windows.yml, controller/ws/ws/handler.go, controller/ws/ws/misc.go, controller/ws/ws/misc_test.go, db/asynctmq/tmq.go, db/asynctmq/tmq_windows.go, db/syncinterface/wrapper.go, db/syncinterface/wrapper_test.go, driver/wrapper/taosc.go, driver/wrapper/taosc_test.go, driver/wrapper/whitelist.go
Jira: https://jira.taosdata.com:18080/browse/TD-
=> feat: use new libtaosnative instead of libtaos in 3.3.6+

db/syncinterface/wrapper_test.go, driver/wrapper/stmt2_test.go
Jira: https://jira.taosdata.com:18080/browse/TD-
=> test: update expected count in stmt2_test.go

.github/workflows/windows.yml, controller/rest/restful.go, controller/rest/restful_test.go
Jira: https://jira.taosdata.com:18080/browse/TD-34382
=> fix: update password validation to remove length check

.github/workflows/build.yml, .github/workflows/macos.yml, config/config.go, config/config_test.go, config/config_windows_test.go, controller/ws/query/ws.go, controller/ws/schemaless/schemaless.go, controller/ws/stmt/stmt.go, controller/ws/tmq/tmq.go, controller/ws/ws/ws.go, db/commonpool/pool.go, example/config/taosadapter.toml, monitor/keeper.go, monitor/keeper_test.go, monitor/metrics/gauge_test.go, thread/locker.go, thread/locker_test.go
Jira: https://jira.taosdata.com:18080/browse/TS-6203
=> feat: enhance monitoring

.github/workflows/build.yml
Jira: https://jira.taosdata.com:18080/browse/TD-
=> chore: update Codecov action to v5 and add support for arm architecture

controller/ws/query/ws.go
=> fix: WebSocket connection log

monitor/keeper.go, monitor/keeper_test.go, monitor/main_test.go, monitor/monitor_test.go
fix: refactor upload ticker logic
Jira: https://jira.taosdata.com:18080/browse/TS-7336
=> fix: refactor upload ticker logic
